### ISSUE TITLE
**Ejercicio N°6 **

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/a14g2-a14g2#10]
6- función potencia. Retorna la potencia del primero elevado al segundo parametros

-[ ] Implementar la funcion
-[ ] Pull Request

**Comment by goose-cba** [comment]
se define la función 'potencia' para dos parámetro (el primero elevado al segundo) utilizando la función pow del lenguaje y se realizan pruebas de escritorio dejando constancia de ellas en el documento.
